{
  "id": 1462714583,
  "name": "Docker",
  "node_id": "WFR_kwLOAlosUs5XL0DX",
  "head_branch": "master",
  "head_sha": "9741eaa731c715b81ec381066995f2e9dcdb1939",
  "run_number": 14696,
  "event": "push",
  "status": "completed",
  "conclusion": "success",
  "workflow_id": 3465823,
  "check_suite_id": 4358515102,
  "check_suite_node_id": "CS_kwDOAlosUs8AAAABA8mpng",
  "url": "https://api.github.com/repos/apache/superset/actions/runs/1462714583",
  "created_at": "2021-11-15T14:52:54Z",
  "updated_at": "2021-11-15T15:09:28Z",
  "run_attempt": 1,
  "run_started_at": "2021-11-15T14:52:54Z",
  "jobs_url": "https://api.github.com/repos/apache/superset/actions/runs/1462714583/jobs",
  "logs_url": "https://api.github.com/repos/apache/superset/actions/runs/1462714583/logs",
  "check_suite_url": "https://api.github.com/repos/apache/superset/check-suites/4358515102",
  "artifacts_url": "https://api.github.com/repos/apache/superset/actions/runs/1462714583/artifacts",
  "cancel_url": "https://api.github.com/repos/apache/superset/actions/runs/1462714583/cancel",
  "rerun_url": "https://api.github.com/repos/apache/superset/actions/runs/1462714583/rerun",
  "previous_attempt_url": null,
  "workflow_url": "https://api.github.com/repos/apache/superset/actions/workflows/3465823",
  "head_commit": {
    "id": "9741eaa731c715b81ec381066995f2e9dcdb1939",
    "tree_id": "756921a51c0549a05fffc28d3e9bda67ef0434b3",
    "message": "Fix 'DataFrame' object has no attribute 'ix' (#12092)\n\nFile \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 2447, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1952, in full_dispatch_request\r\n    rv = self.handle_user_exception(e)\r\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1821, in handle_user_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"/usr/local/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\r\n    raise value\r\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1950, in full_dispatch_request\r\n    rv = self.dispatch_request()\r\n  File \"/usr/local/lib/python3.7/site-packages/flask/app.py\", line 1936, in dispatch_request\r\n    return self.view_functions[rule.endpoint](**req.view_args)\r\n  File \"/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py\", line 109, in wraps\r\n    return f(self, *args, **kwargs)\r\n  File \"/app/superset/utils/log.py\", line 164, in wrapper\r\n    value = f(*args, **kwargs)\r\n  File \"/app/superset/views/core.py\", line 2037, in extra_table_metadata\r\n    mydb, table_name, parsed_schema\r\n  File \"/app/superset/db_engine_specs/presto.py\", line 734, in extra_table_metadata\r\n    table_name, schema_name, database, show_first=True\r\n  File \"/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py\", line 907, in decorated_function\r\n    rv = f(*args, **kwargs)\r\n  File \"/app/superset/db_engine_specs/presto.py\", line 977, in latest_partition\r\n    return column_names, cls._latest_partition_from_df(df)\r\n  File \"/app/superset/db_engine_specs/hive.py\", line 435, in _latest_partition_from_df\r\n    return [df.ix[:, 0].max().split(\"=\")[1]]\r\n  File \"/usr/local/lib/python3.7/site-packages/pandas/core/generic.py\", line 5139, in __getattr__\r\n    return object.__getattribute__(self, name)\r\nAttributeError: 'DataFrame' object has no attribute 'ix'\r\n\r\nCo-authored-by: Ville Brofeldt <ville.v.brofeldt@gmail.com>",
    "timestamp": "2021-11-15T14:52:50Z",
    "author": {
      "name": "minzhang2110",
      "email": "512444693@qq.com"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com"
    }
  }
}
